# Generated by Django 4.0.4 on 2022-06-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlba_site', '0002_urbanimgmultiple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urbanimgmultiple',
            name='urban_tb',
            field=models.IntegerField(),
        ),
    ]
