# Generated by Django 4.0.4 on 2022-06-11 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlba_site', '0003_alter_urbanimgmultiple_urban_tb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urbanimgmultiple',
            name='urban_image_tb',
        ),
        migrations.RemoveField(
            model_name='urbanimgmultiple',
            name='urban_tb',
        ),
        migrations.AddField(
            model_name='urbanimgmultiple',
            name='urban_i_m_tb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urban_i_m_tb', to='mlba_site.urban'),
            preserve_default=False,
        ),
    ]
