# Generated by Django 4.0.4 on 2022-10-25 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlba_site', '0004_remove_urbanimgmultiple_urban_image_tb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urbanimgmultiple',
            name='urban_i_m_tb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urban_i_m_tb', to='mlba_site.urban'),
        ),
    ]
